### ISSUE TITLE
OpenFast and blade dynamics data into Python

### ISSUE THREAD

**Issue by yiannismatt** [OpenFAST/python-toolbox#1]
Hello, Anything here soon? I would like to get the outputs from OPENFast into my Python scripts, especially those of the blade dynamics. I am running Linux, too.

**Comment by rafmudaf** [comment]
There has been some work to consolidate the Python tools that we currently have scattered throughout NREL researchers, but nothing thats ready to be released. The time frame is sometime within the current quarter, so keep an eye out.

At the moment, its primarily input and output parsing and some tools for making system calls to execute a binary.

**Comment by yiannismatt** [comment]
Thank you @rafmudaf. I think I might use the OpenFast Matlab tools in the meantime, calling them from my Python scripts, until there is a fully working OpenFast in Python.
