### ISSUE TITLE
Show FAST simulation progress

### ISSUE THREAD

**Issue by MartinKoch-sowento** [OpenFAST/python-toolbox#17]
Hello, 
thanks for all your work on this toolbox. I have a question regarding the `pyFAST.case_generation.runner` module. Is there any way to show the FAST simulation progress (e.g. "Time 6 of 20 seconds") when running FAST from python? After using your functions I tried a few things myself with the subprocess module but to no avail. 
Best regards,
Martin

**Comment by ebranlard** [comment]
Hi Martin,
For most of the function of the runner, you can set `showOutputs=True` to see the command outputs in the terminal. 
Let me know if that's works,
Emmanuel

**Comment by MartinKoch-sowento** [comment]
Hello Emmanuel, 
thanks for your quick answer. I can see most of the FAST outputs, e.g. the start-up stuff and the simulation summary . The only thing that is missing is the line describing the progress ("Time x of y seconds") so when running long simulations I have no idea how long it will take. I could imagine it is has something to do with the fact that this line is constantly deleted and rewritten. Is the progress line visible and synchronized if you run it on your computer? I'm using PyCharm and I noticed that, strangely enough, the progress is in fact updated in the output if I run the script in debug mode but not in normal mode.

**Comment by ebranlard** [comment]
I've tried it in a regular terminal, by calling `python Example_Parametric.py` with `showOutputs=True`, and the time status was visible and updated. I can imagine that this overwritten line might not be caught by pyCharm depending how their output window is programmed.

**Comment by MartinKoch-sowento** [comment]
okay, then its probably a PyCharm specific issue. Thank you for your help.

**Comment by ebranlard** [comment]
No worries

**Comment by MartinKoch-sowento** [comment]
In case someone else has this problem, I wanted to share a way I found to display the simulation time update in PyCharm using `PIPE` and `universal_newlines=True`:
```python
import subprocess
FAST_EXE = "C:/fast.exe"
MODEL_FILE = "C:/turbine.fst"
process = subprocess.Popen(f'{FAST_EXE} "{MODEL_FILE}"', stdout=subprocess.PIPE, universal_newlines=True)
for line in iter(process.stdout.readline, ""):
    print(line, end="")
process.wait() 
```

**Comment by ebranlard** [comment]
Thanks for that Martin. I guess this approach could be added as an option to `runner.py`.
