### ISSUE TITLE
Is there any documentation or information on python-toolbox?

### ISSUE THREAD

**Issue by tatesnow** [OpenFAST/python-toolbox#23]
I would like to learn the use of python-toolbox and contribute some code, is there any information about it?

**Comment by ebranlard** [comment]
Hi @tatesnow , there is currently no other documentation other than the readme and example files. 
We should probably add an official documentation. To do this we would probably go the route of using readthedocs like the openfast repository, and storing the documentation in a folder "doc". I can probably set the structure up, and then get help on filling up the content. 

If you need a given feature and would like to implement it, the best way would be the start an issue on the repository. We can give some inputs on what would be the best way to implement such feature and how to add it to the repository. I should add a how to contribute on the readme to mention this...

I hope that helps,

Emmanuel

**Comment by tatesnow** [comment]
okay, thank you very much!
