### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by tatesnow** [OpenFAST/python-toolbox#25]
when I run the code of runLinTurbine.py using openfast3.0, The following error message appears：
[FAIL] Input    :  ../../../data/NREL5MW/_5MW_Land_Lin_Trim2/000_ws14.0.fst
       Directory: \GitHub\python-toolbox\pyFAST\linearization\examples
       Command  : C:/Program Files/openfast/openfast_x64.exe ../../../data/NREL5MW/_5MW_Land_Lin_Trim2/000_ws14.0.fst
       Use `showOutputs=True` to debug, or run the command above.
Running: C:/Program Files/openfast/openfast_x64.exe ../../../data/NREL5MW/_5MW_Land_Lin_Trim2/001_ws16.0.fst
[FAIL] Input    :  ../../../data/NREL5MW/_5MW_Land_Lin_Trim2/001_ws16.0.fst
       Directory:\python-toolbox\pyFAST\linearization\examples
       Command  : C:/Program Files/openfast/openfast_x64.exe ../../../data/NREL5MW/_5MW_Land_Lin_Trim2/001_ws16.0.fst
       Use `showOutputs=True` to debug, or run the command above.
Running: C:/Program Files/openfast/openfast_x64.exe ../../../data/NREL5MW/_5MW_Land_Lin_Trim2/002_ws18.0.fst
Traceback (most recent call last):
  File "/GitHub/python-toolbox/pyFAST/linearization/examples/runLinTurbine.py", line 106, in <module>
    eigs = sp.linalg.eig(mbc['AvgA'])[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by ebranlard** [comment]
Hi @tatesnow,  I ran this example just now with openfas3.0 and had no issue. 
Can you run the command: 
         `C:/Program Files/openfast/openfast_x64.exe ../../../data/NREL5MW/_5MW_Land_Lin_Trim2/000_ws14.0.fst` 
from the folder where the file `runLinTurbine.py` is located?  
Make sure you have the latest dev version of  pyFAST just in case, but most likely this is a system issue, where the executable path or the input file path is wrong.

**Comment by tatesnow** [comment]
okay, thank you very much!
