### ISSUE TITLE
Could not find file at SampleFiles/TestCase.bts.

### ISSUE THREAD

**Issue by tatesnow** [OpenFAST/python-toolbox#32]
When I run the code of [python-toolbox](https://github.com/OpenFAST/python-toolbox)/[pyFAST](https://github.com/OpenFAST/python-toolbox/tree/main/pyFAST)/[fastfarm](https://github.com/OpenFAST/python-toolbox/tree/main/pyFAST/fastfarm)/TurbSimInputSetup.ipynb
the error occur
![image](https://user-images.githubusercontent.com/42032942/154214216-143a28b8-2f37-428f-b588-9c1426918387.png)

Can you add this document

**Comment by tatesnow** [comment]
The program you wrote before was very helpful for my research! Thank you! I recently have a very urgent need to run the fast.farm program to study the effect of yaw misalignment of upwind wind turbines on the load pattern of downwind wind turbines. If you have a similar program, please share it with me if it is convenient.

**Comment by ebranlard** [comment]
Hi @tatesnow 
You can find the BTS file here:
      https://github.com/kshaler/FFarmTools/blob/master/SampleFiles/TestCase.bts
    
But I'm going to try to revise and the scripts today, and send an update soon if you don't mind waiting few hours. I'll likely change the interface of the functions a tiny bit and restructure this folder by isolating and simplifying the example.

**Comment by ebranlard** [comment]
Hi @tatesnow 

You'll now find updated examples scripts in this directory:

https://github.com/OpenFAST/python-toolbox/tree/dev/pyFAST/fastfarm/examples

You will need to run `turbsim` on the example tubsim input file to run the second example.

**Comment by tatesnow** [comment]
Thank you very much for your prompt reply, I'll try it now

**Comment by tatesnow** [comment]
Hi @ebranlard 
Your updated program is very concise and easy to understand, and I have it running normally.
I have a small question, how is the **gridheight** determined in fastfarm, I see you set 280
![image](https://user-images.githubusercontent.com/42032942/154451514-00a915b6-ac16-4b2e-bfb3-d716c1888432.png)

**Comment by tatesnow** [comment]
Hi, @ebranlard 
If I want to set different fixed yaw angles for two wind turbines in fastfarm, how should I set them?

**Comment by tatesnow** [comment]
@ebranlard 
I see, thank you very much for your reply!
