### ISSUE TITLE
suggestion for fastfarm programs

### ISSUE THREAD

**Issue by tatesnow** [OpenFAST/python-toolbox#34]
Thank you very much for the program, it has greatly facilitated my research.
When I run the Ex2_FFarmInputSetup.py (change the x/y positions of turbines to [0.0      , 265.643, 653.506,  871.276,  653.901] and [-377.410 , 0.0    ,  -5.378,  28.494 ,  342.903]), and use TestCase.fstf you provides as template file,
![image](https://user-images.githubusercontent.com/42032942/154603138-0b659ae5-f9e1-43bd-a314-896069ab51e1.png)
When I run the program, the newly generated .fstf file contains information for only two WTGs instead of the five WTGs I set up.
The correct .fstf file will not be generated unless I set the WTGs in the template file like the following
![image](https://user-images.githubusercontent.com/42032942/154603683-b22b5580-92b2-4f8c-87c8-c71309ea4bbd.png)
I think this is slightly inconvenient, and if possible, I think some small modifications can be made to this program

**Comment by ebranlard** [comment]
Hi @tatesnow,

I'm aware of this issue. You might notice that there are currently two set of scripts out there on the repo, and I didn't have the time yesterday to merge these two sets of scripts. I'm personally using the the script `fastfarm.py` which I wrote, and there you'll find a function that does write the fastfarm file and account for the change of number of wind turbines. 

   `def writeFastFarm(outputFile, templateFile, xWT, yWT, zWT, FFTS=None, OutListT1=None):`

If you have time, you could use some of the logic in this function to modify the class `FFarmCaseCreation` and achieve the desired behavior.  

I hope that helps

Emmanuel

**Comment by tatesnow** [comment]
Hi @ebranlard,
Thanks for your help! I will try to modify this function

**Comment by ebranlard** [comment]
Thanks a lot if you can help! And thanks again for testing all this. 
Cheers,
Emmanuel
