### ISSUE TITLE
Example_CPLambdaPitch.py

### ISSUE THREAD

**Issue by mufannao** [OpenFAST/python-toolbox#35]
when i run the code of Example_CPLambdaPitch.py, the error occur:
 361     if not flatInputs :
 362         WS_flat    = []
 363         Pitch_flat = []

NameError: name 'flatInputs' is not defined
It seems to be a problem with this "case_gen.CPCT_LambdaPitch" function.
I have been troubled for a long time, looking forward to your reply.

**Comment by mufannao** [comment]
Sorry to all. I solved this problem. After I changed "flatInput" in case_gen.py to "FlatInput", the problem was solved.

**Comment by ebranlard** [comment]
Thanks for noting this, it should have been fixed now.
