### ISSUE TITLE
Rename pyFAST to something else

### ISSUE THREAD

**Issue by ebranlard** [OpenFAST/python-toolbox#38]
Unfortunately the name pyFAST is already taken: https://pypi.org/project/pyFAST/

People attempting to install it by doing `pip install pyFAST` will come up with the wrong repository. 
Also, on the main page of our github repository, projects that use this other library are listed under "Used By"

I'm suggesting to rename the package to: `pyOF`  for pyOpenFAST. It's short and quick to type. 
The change of name will be frustrating to users, but I think it might be useful in the long run.

In this renaming process, I would also like to rename `input_output` to `io`, again, so that it's shorter to type. 

Please let me know your thoughts, and discuss here if you have any suggestions. 

Here's a list of suggestions:
     - pyf    not available (on pypi)
     - pyfast not available (on pypi)
     - pfast
     - pfst
     - pyof
    -  pof
    - poftb

**Comment by ptrbortolotti** [comment]
what about of_toolbox? I'm very much ok with with pyOF, as long as we can push this to PyPI soon and we can start adding it as a dependency to WISDEM and, more importantly, to WEIS

**Comment by ebranlard** [comment]
Sounds good, I'll get to it in the coming weeks.   
It seems `openfast_tools` or `openfast_toolbox` might win (see  https://github.com/OpenFAST/python-toolbox/discussions/60)

**Comment by ebranlard** [comment]
pyFAST has been renamed to `openfast_toolbox` and migrated here: https://github.com/OpenFAST/openfast_toolbox
