### ISSUE TITLE
Poetry PEP440 incompatibility.

### ISSUE THREAD

**Issue by ManuelCazallaGarcia** [OpenFAST/python-toolbox#39]
Hello, when installing with Poetry (a package manager) it returns an error related to PEP440.

Exactly this error: `Invalid PEP 440 version: '-0.1.0-'`

I've pinpointed this error to the pyFast.egg-info folder and in PKG-INFO line 3 changing -0.1.0- to 0.1.0 resolves the issue.

**Comment by ManuelCazallaGarcia** [comment]
Forked and tried to resolve it.

VERSION file instead of "0.1.0" just 0.1.0 seems to do the trick

**Comment by ebranlard** [comment]
Thanks, can you submit a quick pull request into dev?

**Comment by ManuelCazallaGarcia** [comment]
Done, https://github.com/OpenFAST/python-toolbox/pull/40

Like in the PR I can't get it to install without cloning the repository but fixing that is well above my habilites right now.

**Comment by ManuelCazallaGarcia** [comment]
Clearing the cache has enabled me to install it via repository directly. Marked as closed.
