### ISSUE TITLE
DLC .fst file creation 

### ISSUE THREAD

**Issue by kpramng** [OpenFAST/python-toolbox#41]
Hi,

If I want to run DLC 1.2 from 3 m/s to 25 m/s with 6 seeds for each wind speeds, then should I need to create 23 x 1 (wind direction 0 degree only) x 6 (seeds) = 138 .*fst files manually and run them one by one or is there a tool for the same?

For the above task can I use the tool in [https://github.com/OpenFAST/python-toolbox/blob/main/pyFAST/case_generation/examples/Example_Parametric.py](url)

If so, will the tool create the .fst file for all wind speeds?

Also, will the script create the wind files (.bts) also for the simulation or does it have to be generated upfront and somehow the location of the file should be pointed in Example_Parametric.py.

I was getting the below error while running 
`FileNotFoundError: [Errno 2] No such file or directory: '_NREL5MW_Parametric/../5MW_Baseline/NRELOffshrBsline5MW_InflowWind_12mps.dat'`

Just for my understanding, what is the use of this parameter RPM = [10,12,13,15]

Best regards,
Karthik

**Comment by ebranlard** [comment]
Hi @kpramng 

For a simple DLC like 1.2, you can indeed base your case on the Parametric example. You will have to generate all the turbulence boxes beforehand (creating the TurbSim input files, and running TurbSim on them). You can use the python-toolbox to do that, though we don't have a specific example that will generate all the inputs, create a batch, and run them. You can adapt the existing turbsim examples to do that. 

In your OpenFAST parametric study, your InflowWind files have to point to the right turbulence file, something like:
```p['InflowFile|FileName_BTS']='path/to/box_ws{:.1f}_seed{:d}.bts'.format(windspeed, seed)```

To answer your question, the RPM parameter is the rotational speed per minute. In this example, there is no controller, the turbine rotates at a different (constant) speed for each simulation. If there was a controller, this would correspond to the initial rotational speed. 

For more advanced DLC, you can look at the WEIS repository, which should have options to generate them for you: 
https://github.com/WISDEM/WEIS/tree/master


I hope that helps,

Emmanuel

**Comment by kpramng** [comment]
> Hi @kpramng
> 
> For a simple DLC like 1.2, you can indeed base your case on the Parametric example. You will have to generate all the turbulence boxes beforehand (creating the TurbSim input files, and running TurbSim on them). You can use the python-toolbox to do that, though we don't have a specific example that will generate all the inputs, create a batch, and run them. You can adapt the existing turbsim examples to do that.
> 
> In your OpenFAST parametric study, your InflowWind files have to point to the right turbulence file, something like: `p['InflowFile|FileName_BTS']='path/to/box_ws{:.1f}_seed{:d}.bts'.format(windspeed, seed)`
> 
> To answer your question, the RPM parameter is the rotational speed per minute. In this example, there is no controller, the turbine rotates at a different (constant) speed for each simulation. If there was a controller, this would correspond to the initial rotational speed.
> 
> For more advanced DLC, you can look at the WEIS repository, which should have options to generate them for you: https://github.com/WISDEM/WEIS/tree/master
> 
> I hope that helps,
> 
> Emmanuel

Hi @ebranlard ,

Thanks a lot for the reply. 

Is the line,  `p['InflowFile|FileName_BTS']='path/to/box_ws{:.1f}_seed{:d}.bts'.format(windspeed, seed)`
something that I should be adding to the Example_Parametric.py file since I could not find in the original file.

Best regards,
Karthik

**Comment by ebranlard** [comment]
Yes, you would need to add a line "similar" to the one I gave above to make sure that the InflowWind files you generate point to the turbulence file you generate. 

But it seems that before that, you need to make sure you are able to run the Example_Parametric script (which run for constant wind speed and rotor speed). Take the time to read the comments in this script and inspect the folder that is generated: `_NREL5MW_Parametric` to understand which files were generated: one per set of parameters (variable `p` in the script), and with the base name given by `__name__` in the script.  

I'm not sure why you had a `FileNotFoundError` in your previous attempt. The script should work as long as you point to an OpenFAST executable that exists (and of version 3.2 if you are using the `dev` branch of the python-toolbox).
