### ISSUE TITLE
Issue with running Example_PowerCurve_Parametric.py

### ISSUE THREAD

**Issue by FlavieDidier** [OpenFAST/python-toolbox#42]
Hello,

I encounter an error when I tried to run with python Example_PowerCurve_Parametric.py : 

FAST_InitializeAll:SrvD_Init:ParseInputFileInfo:ParseInVar:
 >> A fatal error occurred when parsing data from
 "_NREL5MW_PowerCurveParametric/onshore/NREL5MW_SvD_Simple.dat".
 >> The variable "AfCmode" was not found on line #61.

 OpenFAST encountered an error during module initialization.
 Simulation error level: FATAL ERROR

 Aborting OpenFAST.

(Test) C:\SL\python-toolbox\pyFAST\case_generation\examples>

Can someone give me a pointer to fix this issue, Thanks in advance,
BR,
--Flavie

**Comment by ebranlard** [comment]
Hi @FlavieDidier, 

As you might have noticed, this kind of errors happen when the input files are not at the same version as the openfast executable. 

In this case, the input files of the python-toolbox needed some updating (I have now updated them to version 3.2 / dev)... 




In general, for input file changes you can follow some of the guidelines below:


- Input file changes from one version to the next are documented here:
	https://openfast.readthedocs.io/en/main/source/user/api_change.html 

- You can find up-to-date example input files of the current stable version of OpenFAST here:https://github.com/OpenFAST/r-test/tree/main/glue-codes/openfast 
    - Navigate to  `5MW_Baseline`
        (or another folder that is similar to what you are trying to simulate, e.g.       `5MW_OC4Jckt_DLL_WTurb_WavesIrr_Mgrowth`: OC4 Jacket, DLL controller, Turbulent wind, irregular waves, marine growth)
     
    -  Click on a given file to see its format, copy paste content to a new file on your computer, compare with your input file 

- If you are using a previous version of OpenFAST, clone the r-test repository and checkout the corresponding version tag  (and follow similar steps than above)

      git clone https://github.com/OpenFAST/r-test/
      cd r-test
      git checkout tags/v3.2.0

**Comment by FlavieDidier** [comment]
Hello  @ebranlard,

Thank you for this clear explanation.
Indeed it works when I run it with the correct version of input files.
