### ISSUE TITLE
Simulation of wind over a NREL5MW turbine

### ISSUE THREAD

**Issue by matheusseidel** [OpenFAST/python-toolbox#44]
Hello,

I am new to OpenFAST and I'm having a hard time understanding how to use the software. Sorry if my questions seens silly.

I would like to run the simulation of wind over a NREL5MW turbine. I tried using the `Example_TurbSimBox.py` as an example to study and understand how to use OpenFAST. I was able to run the code and generate some plots, but I didn't quite understand what the code is doing. So I have some basic doubts about the mentioned code:

- What are the geometry and parameters of the simulation? I noticed that the code reads the `TurbSim_WithTwr.bts` file, but how can I open this .bts file to see what exactly is beging simulated?

- How can I see the simulation results? Is there any way to generate the results to read them in ParaView?

Thanks for the help.

**Comment by ebranlard** [comment]
Hi @matheusseidel 
The `Example_TurbSimBox` is an example to look into the data of what we call a turbulence file. These files are used by OpenFAST, to provided wind speed inputs to a simulation. 

If you want to learn about OpenFAST, you'll have to dive into the [openfast documentation ](https://openfast.readthedocs.io/en/dev/index.html). 
We don't have a "quick start" guide yet. We have done a workshop recently, and posted the material [here](https://drive.google.com/drive/folders/1Z6hqCxGP57nZTgyTIMi6AkYd83rJuZmh).

The presentation on "practical usage" might be useful to you. 

Emmanuel

**Comment by matheusseidel** [comment]
> Hi @matheusseidel The `Example_TurbSimBox` is an example to look into the data of what we call a turbulence file. These files are used by OpenFAST, to provide wind speed inputs to a simulation.
> 
> If you want to learn about OpenFAST, you'll have to dive into the [openfast documentation ](https://openfast.readthedocs.io/en/dev/index.html). We don't have a "quick start" guide yet. We have done a workshop recently, and posted the material [here](https://drive.google.com/drive/folders/1Z6hqCxGP57nZTgyTIMi6AkYd83rJuZmh).
> 
> The presentation on "practical usage" might be useful to you.
> 
> Emmanuel

Hello, Emmanuel.

Thanks for the reply and material posted on Drive. I think it will be very useful!
I will watch the recording of the workshop and try to start from there.

Thanks,
Matheus.

**Comment by ebranlard** [comment]
I hope you'll find it useful! Feel free to post other issues here. 
Cheers!
