### ISSUE TITLE
Python based post-processing tool

### ISSUE THREAD

**Issue by kpramng** [OpenFAST/python-toolbox#46]
Hi @ebranlard ,

Are there any Python based tools to do:

- Fatigue DEL calculation from a simulations from cut in to cut out for the lifetime as well as for a timeseries
- Markov's, LDD etc. calculation
- Extreme loads postprocessing

Best regards,
Karthik

**Comment by ebranlard** [comment]
Hi @kpramng 

I've recently reorganized the repository a little bit, and added some fatigue calculation tools. 
You can find an example for the calculation of equivalent load [here](https://github.com/OpenFAST/python-toolbox/blob/dev/pyFAST/postpro/examples/Example_EquivalentLoad.py).
        
It's using the file `fatigue.py`, which was slightly adapted from the [wind energy toolbox](https://gitlab.windenergy.dtu.dk/toolbox/WindEnergyToolbox) (wetb) of DTU. You'll find some Markov matrix calculation in this script. 

The function `equivalent_load` in  `fatigue.py` is a wrapper function, which can use either the wetb version, or `fatpack`. If you want to use `method=fatpack`, you'll need to `pip install fatpack`. Both methods return similar results when the number of bins is 1, for a sinusoidal signal. For other inputs, you'll obtain different results. I don't have an explanation as to why, apart from likely differerent rainflow counting algorithms. 


The [WEIS ](https://github.com/WISDEM/WEIS)repository has tools to compute DEL and postprocessing extreme loads from many OpenFAST simulations, but you'll have to ask on their repository for the usage. The python-toolbox is intended for simple analyses.  Feel free to contribute if you find that some features needs to be added here. 

I hope that helps,
Cheers
