### ISSUE TITLE
Writing SubDyn-file with empty Member Output List

### ISSUE THREAD

**Issue by verlivkra** [OpenFAST/python-toolbox#52]
Hi again, 

I found another bug in the FASTInputFile write-function. I am writing a SubDyn-file using the python-toolbox, and at the moment I don't want to specify any outputs. So I just say` subFile['MemberOuts']   = []`. The SubDyn-file is then correct in that the data under member output list is empty, BUT in addition there is an empty line between the units of the member output list and the SDOutList. 

I fixed this in my local branch, and tested it both with and without empty member output list. Let me know if I should make a pull request.

**Comment by ebranlard** [comment]
Hi @verlivkra 

Yes, thank you so much for doing a pull request. We'll have to check if the tests still pass, that's all.

Thanks again!
