### ISSUE TITLE
fast_input_file not updated for MoorDyn v2 (OpenFAST v3.3.0)?

### ISSUE THREAD

**Issue by verlivkra** [OpenFAST/python-toolbox#54]
For OpenFAST v3.3.0, the MoorDyn-input file does no longer contain information about table sizes. In OpenFAST v3.2.0, number of material types (NTypes), number of connection points (NConnects) and number of lines (NLines) where provided. This is not the case for the MoorDyn-files in v3.3.0. This seems to be an issue when using the FASTInputFile  to read the MoorDyn-input file ('Variable `LineTypes` not found in FAST file). 
My quick-fix is to hard-code the row numbers in NUMTAB_FROM _LAB_DIM_VAR, obviously a short-term solution. Are there any other input-files where the row numbers are not provided for the tables?

**Comment by ebranlard** [comment]
Hi Veronika,

I was afraid this would indeed come, as it is indeed the only input file format from OpenFAST (that I know of) that doesn't specify the number of lines. 

Could you maybe share a couple of these new input files here? 

I'll try to adapt the reader (most likely the easiest will be to write a dedicated one and detect the file format based on the few first lines). 

Cheers!

**Comment by ebranlard** [comment]
Hi this should now be fixed. Let me know if it doesn't work. I've introduced the "AUTO" as a keyword, instead of reading the table dimension from another key in the file, the parser figures the number of lines until a comment character is found (see #57). 
Thanks for reporting this.

**Comment by verlivkra** [comment]
Hi! Apologies for my late response with respect to the input files, and thanks for taking care of this bug. I will let you know if there are some issues.

**Comment by ebranlard** [comment]
no worries :)

**Comment by KlootwijkBart** [comment]
Hi @ebranlard, 

I am using the toolbox to change settings dynamically between openFAST runs, and I am encountering a problem changing the moordyn settings using 'FASTInputFile'. 

I can confirm that reading the MoorDyn v2 file doesn't raise any errors. However, when I try to edit settings and write a new file, I get the following error: 

` Traceback (most recent call last):
  File ~\Anaconda3\envs\floatingh2\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)
  File c:\users\user\code\floating-h2-opt\settings.py:184
    moordyn['Points'] = moordyn['Points']
  File c:\users\user\python-toolbox\pyFAST\input_output\fast_input_file.py:144 in __setitem__
    return self.fixedfile.__setitem__(key,item)
  File c:\users\user\python-toolbox\pyFAST\input_output\fast_input_file.py:257 in __setitem__
    iDimVar = self.getID(dimVar)
  File c:\users\user\python-toolbox\pyFAST\input_output\fast_input_file.py:212 in getID
    raise KeyError('Variable `'+ label+'` not found in FAST file:'+self.filename)
KeyError: 'Variable `AUTO` not found in FAST file:5MW_OC4Semi\\_Template_Files\\5MW_OC4Semi_MoorDyn.dat' `

Please, could you advise how I can solve this in the short term?
