### ISSUE TITLE
python-based script to run turbsim and openfast

### ISSUE THREAD

**Issue by HiHabi** [OpenFAST/python-toolbox#63]
Hi all, 

I am working on constructuring a structural health monitoring system for the tower jacket substructure using OpenFAST and obtain load history data of the upper structure of a wind turbine through OpenFAST. Therefore, I'll have to run manyopenfast cases by modifing the input of Turbsim model to simulate different situations of time-varying loads responses.

Currently, I'm wondering if it's possible to create a python-based script to run the previous mentioned question, and how should I change different input data for Turbsim, InflowWind and OpenFAST module? If possible, how could I create and use the script?

**Comment by ebranlard** [comment]
Hi @HiHabi, 

The way I typically do this is by using the same case generation script as for generating a set of OpenFAST input files. To generate a set of OpenFAST input files, you can have a look at [this example ](https://github.com/OpenFAST/python-toolbox/blob/main/pyFAST/case_generation/examples/Example_Parametric.py)

To generate a set of TurbSim boxes, the principle is the same. I'm enclosing a sample script below. 

```python
import os
import numpy as np
import pyFAST.case_generation.case_gen as case_gen
import pyFAST.case_generation.runner as runner
from pyFAST.input_output.fast_input_file import FASTInputFile

exe          = 'TurbSim_x64.exe'  # path to TurbSim executable
main_file    = 'turbulence_template_dir/Template_TurbSim.dat' # TurbSim input file
workdir      = 'turbulence_gen/'  # Output directory, will be created

template_dir = os.path.dirname(main_file)

# --- Check which keys are available to edit
inp = FASTInputFile(main_file)
print(inp.keys())

# --- Generate list of cases
nSeeds=10
vWS=np.arange(4,22,1)
PARAMS=[]
for WS in vWS:
    for iSeed in np.arange(nSeeds):
        p=dict()
        p['__name__'] = 'WS{:02.0f}_Seed{:02d}'.format(WS,iSeed) # Base for filename
        p['RandSeed1'] = iSeed
        p['URef'] = WS
        PARAMS.append(p)

# --- Write the inputfiles 
inputfiles = case_gen.templateReplaceGeneral(PARAMS, template_dir, outputDir=workdir, main_file=main_file)

# --- Write a set of batch files
# batchFile ='_RunAll.bat'
# writeBatch(batchfile, inputFiles, fastExe=exe, nBatches=2, discard_if_ext_present='.bts')

# --- Run the commands
inputfiles_todo=[s for s in inputfiles if not os.path.exists(s.replace('.dat','.bts'))]
runner.run_cmds(inputfiles_todo, exe, parallel=True, showOutputs=True, nCores=2, showCommand=True)

```

If you use this approach, then you'll need to tell you OpenFAST input files to point to the right turbulence box. In your generation of OpenFAST input file, you'll need something along these lines:

```python
        p['InflowFile|Filename_BTS'] = '"../turbulence_gen/WS{:02.0f}_Seed{:02d}.bts"'.format(WS,iSeed)
```


The [WEIS ](https://github.com/WISDEM/WEIS)framework likely has tools to automatically generate DLCs. You can ask about it on their repository. I personnaly prefer the granularity of pyFAST. 

I hope that helps.
