### ISSUE TITLE
there is no postpro function in pyFAST.input_output

### ISSUE THREAD

**Issue by tatesnow** [OpenFAST/python-toolbox#9]
there is no postpro function in pyFAST.input_output, when i run the Example_Parametric.py, there are some error.

**Comment by ebranlard** [comment]
Thanks for pointing that out, I've added the package, let me know if you see any other issues.

**Comment by tatesnow** [comment]
thank you very much!
















At 2021-01-01 07:19:35, "E. Branlard" <notifications@github.com> wrote:

Thanks for pointing that out, I've added the package, let me know if you see any other issues.
